# GoPro constants as defined in https://docs.google.com/document/d/1CcYOCZRw9C4sIQu4xDXjPMkxZYROmTLB0EtpZamnq74/edit#

GOPRO_V1_SPEC_VERSION = 1
GOPRO_V2_SPEC_VERSION = 2

CAPTURE_MODE_VIDEO = 0
CAPTURE_MODE_PHOTO = 1
CAPTURE_MODE_BURST = 2 # Burst only for Hero 3+
CAPTURE_MODE_TIMELAPSE = 3
CAPTURE_MODE_MULTISHOT = 4 # Multishot only for Hero4 

SHUTTER_STATUS_STOP_VIDEO = 0
SHUTTER_STATUS_START_VIDEO = 1
SHUTTER_STATUS_STOP_BURST = 2
SHUTTER_STATUS_START_BURST = 3

MODEL_NONE = 0
MODEL_HERO3PLUS_SILVER = 10
MODEL_HERO3PLUS_BLACK = 11

STATUS_NO_GOPRO = 0
STATUS_INCOMPATIBLE_GOPRO = 1
STATUS_GOPRO_CONNECTED = 2
STATUS_GOPRO_ERROR = 3

RECORD_COMMAND_STOP = 0
RECORD_COMMAND_START = 1
RECORD_COMMAND_TOGGLE = 2

VIDEO_FORMAT_NTSC = 0
VIDEO_FORMAT_PAL = 1
