# Packet IDs. These must match "enum MsgID" in artoo/src/hostprotocol.h.
PKT_ID_NOP = 0
PKT_ID_DSM = 1
PKT_ID_CAL = 2
PKT_ID_SYSINFO = 3
PKT_ID_MAVLINK = 4
PKT_ID_SET_RAW_IO = 5
PKT_ID_RAW_IO_REPORT = 6
PKT_ID_PAIR_REQUEST = 7
PKT_ID_PAIR_CONFIRM = 8
PKT_ID_PAIR_RESULT = 9
PKT_ID_SHUTDOWN_REQUEST = 10 
